syntax on
set ambiwidth=double
set backspace=indent,eol,start
set clipboard+=unnamed
set cursorline
set hidden
set hlsearch
set incsearch
set number
set ruler
set shiftwidth=4
set smartindent
set tabstop=4
set title
set t_vb=
set novisualbell
